name: Docker Client Image CI

on:
  push:
    paths:
      - 'client/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Docker hub login
      env:
        DOCKER_USER: ${{secrets.DOCKER_HUB_USER}}
        DOCKER_PASS: ${{secrets.DOCKER_HUB_PASS}}
      run: docker login -u $DOCKER_USER -p $DOCKER_PASS
    - name: Build client docker image
      run: docker build -t babakt/ppt-client:cadvise ./client/
    - name: Push the image to docker hub
      run: docker push babakt/ppt-client:cadvise